.TH DUNSTMERGE 1 2018\-07\-09 Linux "User Manuals"
.SH NAME
.PP
\fB\fCdunstmerge\fR \- Dunst layout manager

.SH SYNOPSIS
.PP
\fB\fCdunstmerge\fR [\fB\fC\-v\fR|\fB\fC\-h\fR] [\fB\fC\-c\fR \fIconfig\-file\fP] \fIfile\fP ...
\fB\fCdunstmerge\fR [\fILAYOUT\fP]

.SH DESCRIPTION
.PP
\fB\fCdunstmerge\fR merges three different files inside \fIDUNST\_DIR\fP
into one dunstrc file. The files that gets merged are:

.RS
.IP \(bu 2
dunst\-theme
.br
.IP \(bu 2
layouts/LAYOUT
.br
.IP \(bu 2
dunst\-settings
.br

.RE

.PP
If \fILAYOUT\fP is omitted \fB\fCdunstmerge\fR will look in the
current \fB\fCdunstrc\fR file for the name of the current layout
and use that, which will result in a reload of dunst.
If \fIlayouts/LAYOUT\fP doesn't exist, \fIdefault\fP will be used.

.PP
The advantage of using this is that it will be easy
to manage multiple layouts and themes, that can
be independently generated.

.PP
If the directory \fIDUNST\_DIR/layouts\fP doesnt exist,
\fB\fCdunstmerge\fR will split the current (or the default)
\fIdunstrc\fP file and create a default layout the first
time \fB\fCdunstmerge\fR is executed. It will also create
\fIdunst\-theme\fP and \fIdunst\-settings\fP and copy any old
dunstrc to \fIDUNST\_DIR/dunstrc\-orginal\fP\&. It will also
copy the default dunstrc to \fIDUNST\_DIR/dunstrc\-default\fP\&.

.SH OPTIONS
.PP
\fB\fC\-v\fR
  Show version and exit.

.PP
\fB\fC\-h\fR
  Show help and exit.

.SH FILES
.PP
\fIDUNST\_DIR\fP
.br
Directory containing the dunst configuration files, themes
and layouts.

.PP
\fIDUNST\_DIR/dunstrc\fP
.br
This file will get generated by \fB\fCdunstmerge\fR and used by
\fB\fCdunst\fR\&.

.PP
\fIDUNST\_DIR/dunstrc\-original\fP
.br
If a dunstrc file existed prior to the first time \fB\fCdunstrc\fR,
was executed, that file will be copied here.

.PP
\fIDUNST\_DIR/dunstrc\-default\fP
.br
This is just a copy of \fI/usr/share/dunst/dunstrc\fP for
reference. It has very good comments.

.PP
\fIDUNST\_DIR/dunst\-theme\fP
.br
Contains theme specific settings, such as colors and icons.

.PP
\fIDUNST\_DIR/layouts/LAYOUT\fP
.br
Layout specific settings, such as geometry and text options.

.PP
\fIDUNST\_DIR/layouts/default\fP
.br
default layout file.

.PP
\fIDUNST\_DIR/dunst\-settings\fP
.br
Other \fIglobal\fP dunst settings that are independent of the
theme or the layout.

.PP
\fIDUNST\_DIR/dunst\-default\fP
.br
Default dunstrc, copied from \fI/usr/share/dunst/dunstrc\fP

.SH DEPENDENCIES
.PP
dunst

.SH AUTHOR
.PP
budRich 
\[la]robstenklippa@gmail.com\[ra]

\[la]https://budrich.github.io\[ra]

.SH SEE ALSO
.PP
dunst(1), dunstify, notify\-send, mondo(1)
